server:
  port: 8080
#  servlet:
#    context-path: /v1/api/aquam
  error:
    path: /error

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aquam
    username: postgres
    password: 40571187
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true